#Local
spring: 
   config:
      activate:
         on-profile: dev
         
   security:
      oauth2:
         client:
            registration:
               google:
                  client-id: 145515520825-eevbkd63eeodisvskd6ukt22290qll85.apps.googleusercontent.com
                  client-secret: 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
                  scope: profile, email
                  redirect-uri: http://localhost:8080/oauth2/callback/google
                  client-name: google                           
               naver:
                  client-id: kzPIt1JjXH8gdHgK3rlN
                  client-secret: ripEAIWt4z
                  redirect-uri: http://localhost:8080/oauth2/callback/naver
                  authorization-grant-type: authorization_code
                  client-name: naver
               kakao:
                  client-id: 53c5f9b54ad9450a6cc811fdccf65417
                  client-secret: lk1pcea1Vsf0NhDIlSleM7sK57rumIhO
                  redirect-uri: http://localhost:8080/oauth2/callback/kakao
                  authorization-grant-type: authorization_code
                  client-name: kakao
                  client-authentication-method: POST
                  scope: profile_nickname,profile_image,account_email
            provider:
               naver:
                  authorization-uri: https://nid.naver.com/oauth2.0/authorize
                  token-uri: https://nid.naver.com/oauth2.0/token
                  user-info-uri: https://openapi.naver.com/v1/nid/me
                  user-name-attribute: response
               kakao:
                  authorization-uri: https://kauth.kakao.com/oauth/authorize
                  token-uri: https://kauth.kakao.com/oauth/token
                  user-info-uri: https://kapi.kakao.com/v2/user/me
                  user-name-attribute: id

logging:
  config: classpath:log4j2.xml
                  
                      
jwt:
   toekn-issuer: foo.com
   token-name: foo-app-jwt
   #secret: 12345
   secret: 123456789
   expire-time: 90 #sec

# 프론트엔드 애플리케이션은 어차피 SPA
frontend-app:
   entry: /index.html

my-props:    
   name:
      point: 200

---

#Production
spring: 
   config:
      activate:
         on-profile: prod 
         
         
   security:
      oauth2:
         client:
            registration:
               google:
                  client-id: 
                  client-secret: 
                  scope: profile
                  redirect-uri: 
                  client-name: google                           
               naver:
                  client-id: 
                  client-secret:  
                  redirect-uri: 
                  authorization-grant-type: authorization_code
                  client-name: naver
               kakao:
                  client-id: 53c5f9b54ad9450a6cc811fdccf65417
                  client-secret: lk1pcea1Vsf0NhDIlSleM7sK57rumIhO
                  redirect-uri: http://localhost:8080/oauth2/callback/kakao
                  authorization-grant-type: authorization_code
                  client-name: kakao
            provider:
               naver:
                  authorization-uri: https://nid.naver.com/oauth2.0/authorize
                  token-uri: https://nid.naver.com/oauth2.0/token
                  user-info-uri: https://openapi.naver.com/v1/nid/me
                  user-name-attribute: response
               kakao:
                  authorization-uri: https://kauth.kakao.com/oauth/authorize
                  token-uri: https://kauth.kakao.com/oauth/token
                  user-info-uri: https://kapi.kakao.com/v2/user/me
                  user-name-attribute: id
                  
logging:
  config: classpath:log4j2.xml
                              

jwt:
   toekn-issuer: foo.com
   token-name: foo-app-jwt
   secret: 12345
   expire-time: 300 #sec

frontend-app:
   entry: /index.html
   
my-props:    
   name:
      point: 200
